version: '3'

services:
  gmco-ticketing-fe:
    image: trahganjil/gmco-ticketing-fe:${DOCKER_TAG}
    restart: unless-stopped
    container_name: gmco_fe
    ports:
      - "127.0.0.1:3001:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gmco-fe-dev-http.rule=Host(`dev.gmco-event.com`)"
      - "traefik.http.routers.gmco-fe-dev-http.entrypoints=web"
      - "traefik.http.routers.gmco-fe-dev-http.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.gmco-fe-dev-http.service=noop@internal"
      - "traefik.http.routers.gmco-fe-dev-https.rule=Host(`dev.gmco-event.com`)"
      - "traefik.http.routers.gmco-fe-dev-https.entrypoints=websecure"
      - "traefik.http.routers.gmco-fe-dev-https.tls=true"
      - "traefik.http.routers.gmco-fe-dev-https.tls.certresolver=letsencrypt"
    networks:
      - gateway_ingress

networks:
  gateway_ingress:
    external: true
