name: Docker Image CI

on:
  push:
    branches:
      - master
      - main
      - development

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Build the Dockerimage
        run: docker build . --file Dockerfile --tag trahganjil/gmco-ticketing-fe:$(git rev-parse --short HEAD)
      - name: Push to Docker Hub
        run: docker login -u ${{ secrets.DH_USER }} -p ${{ secrets.DH_PASS }} && docker push trahganjil/gmco-ticketing-fe:$(git rev-parse --short HEAD)
